services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - react-express-mongo-network
    
  socket:
    build: ./socket
    ports:
      - "9000:9000"
    depends_on:
      - server
    volumes:
      - ./socket:/app
      - /app/node_modules
    networks:
      - react-express-mongo-network
    
  server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - react-express-mongo-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - react-express-mongo-network

volumes:
  mongo-data:

networks:
  react-express-mongo-network:
    driver: bridge
